// GENERATED CODE - DO NOT MODIFY MANUALLY
// **************************************************************************
// Auto generated by https://github.com/fluttercandies/ff_annotation_route
// **************************************************************************
// fast mode: true
// version: 10.0.10
// **************************************************************************
// ignore_for_file: prefer_const_literals_to_create_immutables,unused_local_variable,unused_import,unnecessary_import,unused_shown_name,implementation_imports,duplicate_import
/// The routeNames auto generated by https://github.com/fluttercandies/ff_annotation_route
const List<String> routeNames = <String>[
  'fluttercandies://ChatDemo',
  'fluttercandies://ChatDemo1',
  'fluttercandies://TextInput',
  'fluttercandies://demogrouppage',
  'fluttercandies://mainpage',
];

/// The routes auto generated by https://github.com/fluttercandies/ff_annotation_route
class Routes {
  const Routes._();

  /// 'Show how to build chat page which include custom keyboard with KeyboardBuilder quickly'
  ///
  /// [name] : 'fluttercandies://ChatDemo'
  ///
  /// [routeName] : 'ChatDemo'
  ///
  /// [description] : 'Show how to build chat page which include custom keyboard with KeyboardBuilder quickly'
  ///
  /// [constructors] :
  ///
  /// ChatDemo : [Key? key]
  ///
  /// [exts] : {'order': 0, 'group': 'Simple'}
  static const String fluttercandiesChatDemo = 'fluttercandies://ChatDemo';

  /// 'Show how to build chat page which include custom keyboard with TextInputBuilder quickly'
  ///
  /// [name] : 'fluttercandies://ChatDemo1'
  ///
  /// [routeName] : 'ChatDemo1'
  ///
  /// [description] : 'Show how to build chat page which include custom keyboard with TextInputBuilder quickly'
  ///
  /// [constructors] :
  ///
  /// ChatDemo1 : [Key? key]
  ///
  /// [exts] : {'order': 1, 'group': 'Simple'}
  static const String fluttercandiesChatDemo1 = 'fluttercandies://ChatDemo1';

  /// 'Show how to build custom TextInput quickly'
  ///
  /// [name] : 'fluttercandies://TextInput'
  ///
  /// [routeName] : 'TextInput'
  ///
  /// [description] : 'Show how to build custom TextInput quickly'
  ///
  /// [constructors] :
  ///
  /// TextInputDemo : [Key? key]
  ///
  /// [exts] : {'order': 2, 'group': 'Simple'}
  static const String fluttercandiesTextInput = 'fluttercandies://TextInput';

  /// 'DemoGroupPage'
  ///
  /// [name] : 'fluttercandies://demogrouppage'
  ///
  /// [routeName] : 'DemoGroupPage'
  ///
  /// [constructors] :
  ///
  /// DemoGroupPage : [Key? key, MapEntry<String, List<DemoRouteResult>>(required) keyValue]
  static const String fluttercandiesDemogrouppage =
      'fluttercandies://demogrouppage';

  /// 'MainPage'
  ///
  /// [name] : 'fluttercandies://mainpage'
  ///
  /// [routeName] : 'MainPage'
  ///
  /// [constructors] :
  ///
  /// MainPage : [Key? key]
  static const String fluttercandiesMainpage = 'fluttercandies://mainpage';
}
