// GENERATED CODE - DO NOT MODIFY MANUALLY
// **************************************************************************
// Auto generated by https://github.com/fluttercandies/ff_annotation_route
// **************************************************************************
// fast mode: true
// version: 10.0.10
// **************************************************************************
// ignore_for_file: prefer_const_literals_to_create_immutables,unused_local_variable,unused_import,unnecessary_import,unused_shown_name,implementation_imports,duplicate_import
/// The routeNames auto generated by https://github.com/fluttercandies/ff_annotation_route
const List<String> routeNames = <String>[
  'fluttercandies://ChatDemo',
  'fluttercandies://TestPage',
  'fluttercandies://TestPage1',
  'fluttercandies://demogrouppage',
  'fluttercandies://mainpage',
];

/// The routes auto generated by https://github.com/fluttercandies/ff_annotation_route
class Routes {
  const Routes._();

  /// 'Show how to build chat list quickly'
  ///
  /// [name] : 'fluttercandies://ChatDemo'
  ///
  /// [routeName] : 'ChatDemo'
  ///
  /// [description] : 'Show how to build chat list quickly'
  ///
  /// [constructors] :
  ///
  /// ChatDemo : [Key? key]
  ///
  /// [exts] : {'order': 0, 'group': 'Simple'}
  static const String fluttercandiesChatDemo = 'fluttercandies://ChatDemo';

  /// 'Show how to build chat list quickly'
  ///
  /// [name] : 'fluttercandies://TestPage'
  ///
  /// [routeName] : 'TestPage'
  ///
  /// [description] : 'Show how to build chat list quickly'
  ///
  /// [constructors] :
  ///
  /// TestPage : [Key? key]
  ///
  /// [exts] : {'order': 10, 'group': 'Simple'}
  static const String fluttercandiesTestPage = 'fluttercandies://TestPage';

  /// 'Show how to build chat list quickly'
  ///
  /// [name] : 'fluttercandies://TestPage1'
  ///
  /// [routeName] : 'TestPage1'
  ///
  /// [description] : 'Show how to build chat list quickly'
  ///
  /// [constructors] :
  ///
  /// TestPage1 : [Key? key]
  ///
  /// [exts] : {'order': 10, 'group': 'Simple'}
  static const String fluttercandiesTestPage1 = 'fluttercandies://TestPage1';

  /// 'DemoGroupPage'
  ///
  /// [name] : 'fluttercandies://demogrouppage'
  ///
  /// [routeName] : 'DemoGroupPage'
  ///
  /// [constructors] :
  ///
  /// DemoGroupPage : [Key? key, MapEntry<String, List<DemoRouteResult>>(required) keyValue]
  static const String fluttercandiesDemogrouppage =
      'fluttercandies://demogrouppage';

  /// 'MainPage'
  ///
  /// [name] : 'fluttercandies://mainpage'
  ///
  /// [routeName] : 'MainPage'
  ///
  /// [constructors] :
  ///
  /// MainPage : [Key? key]
  static const String fluttercandiesMainpage = 'fluttercandies://mainpage';
}
